### ISSUE TITLE
MAUI: TrackerChanged event is not being called in iOS when tapping the points.

### ISSUE THREAD

**Issue by melo-dev** [oxyplot/oxyplot-maui#20]
The TrackerChanged event is not being called in iOS when tapping the points. In Android, it is working fine. 

Code:
 LineSeries lineSeries = new LineSeries
                {
                    StrokeThickness = 1,
                    CanTrackerInterpolatePoints = false,
                    LineStyle = LineStyle.Solid,
                    MarkerFill = OxyColors.Black,
                    Color = OxyColors.Black,
                    MarkerStroke = OxyColors.Black,
                    MarkerType = MarkerType.Circle,
                    MarkerSize = 1,
                    TextColor = OxyColors.Black
                };

MyPlotModel.Series.Add(lineSeries);
lineSeries.Points.Add(new DataPoint(0, 10));
lineSeries.Points.Add(new DataPoint(1, 20));

MyPlotModel.TrackerChanged += ChartModel_TrackerChanged;
 private void ChartModel_TrackerChanged(object sender, TrackerEventArgs e)
{ 
   //breakpoint added here.
}

Using iPhone X.
Installed Nuget Package: OxyPlot.Maui.Skia v1.0.2

**Comment by janusw** [comment]
I tried to reproduce this problem with the `OxyplotMauiSample` app, but failed. I see TrackerChanged events both on Android and iOS.

So either you're doing something funny or the problem only occurs under specific conditions. We'd need a proper reproducer to make any progress with this ...

**Comment by janusw** [comment]
> I tried to reproduce this problem with the `OxyplotMauiSample` app, but failed. I see TrackerChanged events both on Android and iOS.

FYI, here are the changes that I made to the sample app. I pushed them to this branch (on my fork):

https://github.com/janusw/oxyplot-maui/commits/issue20_repro/

@melo-dev Can you confirm that the `TrackerChanged` events work correctly for this use case (on iOS)?

**Comment by melo-dev** [comment]
I forgot to mention that my XCode was 15.4, but after upgrading to Xcode 16.1 it is working correctly now.

**Comment by janusw** [comment]
Actually I could not even reproduce it with XCode 15.4, using this global.json file:

```
{
  "sdk": {
    "version": "8.0.402",
    "workloadVersion": "8.0.402",
    "rollForward": "patch"
  }
}
```

I guess we can close this issue?
