### ISSUE TITLE
HandlerNotFound exception

### ISSUE THREAD

**Issue by ketakidevendra** [oxyplot/oxyplot-maui#4]
I simply created a sample example and tried to use this library for MAUI .NET 7. It throws exception.
![image](https://github.com/oxyplot/oxyplot-maui/assets/53600181/6dae180f-6e39-4b38-bd71-5b078670a8e7)

**Comment by janusw** [comment]
You probably just need to call `UseSkiaSharp()` on your `MauiAppBuilder`, see our sample: https://github.com/oxyplot/oxyplot-maui/blob/e9f0ae3c78de4faca96059fa172f53457ca82701/Source/OxyplotMauiSample/MauiProgram.cs#L13

**Comment by janusw** [comment]
Sorry, did not mean to close just yet. Can you confirm that the above fixes the error?

**Comment by ketakidevendra** [comment]
Thanks! It was my fault. Issue is solved.

**Comment by janusw** [comment]
> Thanks! It was my fault. Issue is solved.

Awesome. So I'll close it after all 😄
